### ISSUE TITLE
ktmpl doesn't replace variable if it is inside a key name

### ISSUE THREAD

**Issue by sSpeaker** [jimmycuadra/ktmpl#1]
This is part of kops config. 
`cloudLabels:
      kubernetes.io/cluster/$(CLUSTER_NAME): owned
`
ktmpl does not replace this variable.

**Comment by jimmycuadra** [comment]
This is addressed in the new 0.9.0 release: https://github.com/jimmycuadra/ktmpl/releases/tag/0.9.0

Thanks for reporting!
