### ISSUE TITLE
ktmpl version on homebrew repo is out of date

### ISSUE THREAD

**Issue by davidarich** [jimmycuadra/ktmpl#2]
The latest available version of ktmpl on homebrew is version 0.7.0. Is it possible to update the package to the latest release (0.9.0)?

```
$ brew info ktmpl | head -n1
ktmpl: stable 0.7.0 (bottled), HEAD
```

**Comment by jimmycuadra** [comment]
Anyone can do this, it turns out. Instructions are here: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

I just gave it a shot but ran into a bunch of errors and don't have time to look into it further right now.

**Comment by davidarich** [comment]
Thanks, I didn't realize anyone could update package versions for Homebrew. I submitted a PR for 0.9.0. https://github.com/Homebrew/homebrew-core/pull/37820
